Repository lmc-eu/jobs-design-system, pull requests merged in 2022-09, with the labels that each got.

#22 Docs: Correct Jobs Design System description
  README.md
Labels: documentation

#23 Chore(design-tokens): Remove `prepare` script
  packages/design-tokens/package.json
Labels: maintenance

#26 Feat(icons): Manually update icons from Supernova
  packages/icons/src/svg/culture.svg
  packages/icons/src/svg/dog-friendly.svg
  packages/icons/src/svg/loading.svg
  packages/icons/src/svg/medical-care.svg
  packages/icons/src/svg/motivational-program.svg
Labels: feature
