Repository lmc-eu/jobs-design-system, pull requests merged in 2022-03, with the labels that each got.

#3 Feat: Introduce public Sass endpoints
  src/scss/@tokens.scss
  src/scss/index.scss
Labels: feature

#4 Chore: Introduce basic configured dev stack
  .commitlintrc.js
  .editorconfig
  .gitignore
  .prettierignore
  .prettierrc.js
  .renovaterc.json
  .stylelintrc.js
  package.json
  yarn.lock
Labels: maintenance

#7 Chore/publish
  .github/workflows/publish.yaml
  .github/workflows/test.yaml
Labels: feature, maintenance

#8 Chore(ci): Fix unexpected end of expression
  .github/workflows/publish.yaml
Labels: maintenance

#9 Chore(ci): Add required github token for get merged pr action
  .github/workflows/publish.yaml
Labels: maintenance

#10 Chore(ci): Set NPM_AUTH_TOKEN for npm registry
  .github/workflows/publish.yaml
Labels: maintenance

#11 Docs: How to contribute to this package
  README.md
Labels: documentation

#13 Chore: Fix missing `--` in keyword argument
  .github/workflows/publish.yaml
Labels: feature
